# Generated by Django 4.0.4 on 2022-06-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pnickname', models.CharField(max_length=50)),
                ('pno', models.IntegerField()),
                ('pscore', models.IntegerField()),
                ('pbirthdate', models.DateField()),
                ('pstatus', models.BooleanField()),
            ],
            options={
                'db_table': 'player',
            },
        ),
    ]
