# Generated by Django 4.0.4 on 2022-05-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='reporterName',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
