# Generated by Django 4.0.4 on 2022-06-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor1',
            name='gender',
            field=models.IntegerField(choices=[('male', 'Male'), ('female', 'Female')], null=True),
        ),
    ]
