# Generated by Django 4.0.4 on 2022-06-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('isActive', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=20)),
                ('rollno', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
